### PR TITLE
Added support for ':global' selector for css-modules (css-loader)

### PR DESCRIPTION
**Pull request by 4eb0da**
I don't know everything about css modules, right now i'm trying to fix usage of css modules in my project with simple solution

https://github.com/css-modules/css-modules

### CODE REVIEW

**Comment by jacobp100** [comment]
Yeah, seems fine. Could you just add a note in the README about this?

**Comment by 4eb0da** [comment]
Sure! Done
Or you mean separate bigger note about that?

**Comment by jacobp100** [comment]
I've added a reminder to publish when I'm back on my personal laptop

**Comment by jacobp100** [comment]
Thanks!

**Comment by 4eb0da** [comment]
A humble reminder about new version)

**Comment by 4eb0da** [comment]
@jacobp100 
A humble reminder about new version 2)

**Pull request merged**
